services:
  - docker
sudo: required

script:
  # - docker login -u=${DOCKER_USER} -p=${DOCKER_PASSWORD}

  # uncomment these lines if you want to build and push base tools
  - git clone https://github.com/VSChina/magic-modules/ ~/magic-modules
  - cd ~/magic-modules; git checkout azure_backend
  - cd -
  - docker build --tag zikalino/autorest.cli.base -f Dockerfile-base .
  # - docker push zikalino/autorest.cli.base

  - docker build --tag zikalino/autorest.cli .
  # - docker push zikalino/autorest.cli

  - git clone https://github.com/Azure/azure-rest-api-specs.git ~/azure-rest-api-specs
  - git clone https://audevbot:${GH_TOKEN}@github.com/audevbot/autorest.cli.debug.git ~/autorest.cli.debug
  - git clone https://audevbot:${GH_TOKEN}@github.com/Azure/magic-module-specs.git ~/magic-module-specs;
  # - git clone https://audevbot:$(GH_TOKEN)@github.com/chunyu3/terraform.git ~/terraform;
  - git clone https://chunyu3:${TF_TOKEN}@github.com/chunyu3/terraform.git ~/terraform;
  - export CURRENT_PATH=$(pwd)
  - cd ~/autorest.cli.debug; git checkout autogenerated-${TRAVIS_BUILD_NUMBER} -- ~/autorest.cli.debug || git checkout -B autogenerated-${TRAVIS_BUILD_NUMBER}
  - mkdir -p ~/autorest.cli.debug/generated
  - rm -rf ~/autorest.cli.debug/generated/*
  - mkdir -p ~/mmoutput

  - 'cd $CURRENT_PATH/input;
     for d in *; do
        echo ---------------------------------------------------------------------------------;
        echo Processing: $d;
        echo ---------------------------------------------------------------------------------;
        docker run -t -i
        -v ~/azure-rest-api-specs:/azure-rest-api-specs
        -v ~/autorest.cli.debug/generated:/generated
        -v ~/magic-modules:/magic-modules
        -v ~/mmoutput:/mmoutput
        zikalino/autorest.cli
        /autorest.cli/input/$d;
        break;
     done'

after_success:
  - echo "success"
  - ls -al ~/autorest.cli.debug/generated
  - ls -al ~/autorest.cli.debug/generated/magic-modules-input
  - ls -al ~/autorest.cli.debug/generated/ansible-module-drafts
  # - git config --global user.email "audevbot@microsoft.com"
  # - git config --global user.name "audevbot"
  - cd ~/autorest.cli.debug ; git config credential.helper store
  - cd ~/magic-module-specs; git config credential.helper store
  # - cd ~/terraform; git config credential.helper store
  # - echo "https://audevbot:${GH_TOKEN}@github.com" > ~/.git-credentials

  # - cd ~/autorest.cli.debug ; git add -A ; git commit -m "autogenerated-${TRAVIS_BUILD_NUMBER}" ; git push --set-upstream origin autogenerated-${TRAVIS_BUILD_NUMBER}
  - cp -R ~/autorest.cli.debug/generated/magic-modules-input ~/terraform
  - cp -R ~/mmoutput ~/terraform
  - ls -al ~/terraform
  - cd ~/terraform; git config credential.helper store
  - echo "https://chunyu3:${TF_TOKEN}@github.com" > ~/.git-credentials
  - cat ~/.git-credentials
  # - git config --global user.email "yuchun_green@hotmail.com"
  # - git config --global user.name "chunyu3"
  - cd ~/terraform; git add -A; git commit -m "autogenerated"; git push --set-upstream origin master;



  # - cd ~/magic-module-specs; (git checkout autogenerated-${TRAVIS_BUILD_NUMBER} || git checkout -B autogenerated-${TRAVIS_BUILD_NUMBER}) #; rm -rf products

  # validated modules
 
  # - export MODULE=apimanagementapidiagnostic
  # - cd ~/magic-module-specs; git checkout master; (git checkout autogenerated-${MODULE} || git checkout -B autogenerated-${MODULE})
  # - cp -R ~/autorest.cli.debug/generated/magic-modules-input/${MODULE} ~/magic-module-specs/specs
  # - cd ~/magic-module-specs ; git add -A ; git commit -m "autogenerated-${MODULE}" ; git push --set-upstream origin autogenerated-${MODULE}

  # - export MODULE=apimanagementapirelease
  # - cd ~/magic-module-specs; git checkout master; (git checkout autogenerated-${MODULE} || git checkout -B autogenerated-${MODULE})
  # - cp -R ~/autorest.cli.debug/generated/magic-modules-input/${MODULE} ~/magic-module-specs/specs
  # - cd ~/magic-module-specs ; git add -A ; git commit -m "autogenerated-${MODULE}" ; git push --set-upstream origin autogenerated-${MODULE}

  # - export MODULE=frontdoorbackendpool
  # - cd ~/magic-module-specs; git checkout master; (git checkout autogenerated-${MODULE} || git checkout -B autogenerated-${MODULE})
  # - cp -R ~/autorest.cli.debug/generated/magic-modules-input/${MODULE} ~/magic-module-specs/specs
  # - cd ~/magic-module-specs ; git add -A ; git commit -m "autogenerated-${MODULE}" ; git push --set-upstream origin autogenerated-${MODULE}

  # - export MODULE=frontdoorfrontendendpoint
  # - cd ~/magic-module-specs; git checkout master; (git checkout autogenerated-${MODULE} || git checkout -B autogenerated-${MODULE})
  # - cp -R ~/autorest.cli.debug/generated/magic-modules-input/${MODULE} ~/magic-module-specs/specs
  # - cd ~/magic-module-specs ; git add -A ; git commit -m "autogenerated-${MODULE}" ; git push --set-upstream origin autogenerated-${MODULE}

  # - export MODULE=frontdoorhealthprobesetting
  # - cd ~/magic-module-specs; git checkout master; (git checkout autogenerated-${MODULE} || git checkout -B autogenerated-${MODULE})
  # - cp -R ~/autorest.cli.debug/generated/magic-modules-input/${MODULE} ~/magic-module-specs/specs
  # - cd ~/magic-module-specs ; git add -A ; git commit -m "autogenerated-${MODULE}" ; git push --set-upstream origin autogenerated-${MODULE}

  # - export MODULE=frontdoorloadbalancingsetting
  # - cd ~/magic-module-specs; git checkout master; (git checkout autogenerated-${MODULE} || git checkout -B autogenerated-${MODULE})
  # - cp -R ~/autorest.cli.debug/generated/magic-modules-input/${MODULE} ~/magic-module-specs/specs
  # - cd ~/magic-module-specs ; git add -A ; git commit -m "autogenerated-${MODULE}" ; git push --set-upstream origin autogenerated-${MODULE}

  # - export MODULE=batchcertificate
  # - cd ~/magic-module-specs; git checkout master; (git checkout autogenerated-${MODULE} || git checkout -B autogenerated-${MODULE})
  # - cp -R ~/autorest.cli.debug/generated/magic-modules-input/${MODULE} ~/magic-module-specs/specs
  # - cd ~/magic-module-specs ; git add -A ; git commit -m "autogenerated-${MODULE}" ; git push --set-upstream origin autogenerated-${MODULE}

  # - export MODULE=batchpool
  # - cd ~/magic-module-specs; git checkout master; (git checkout autogenerated-${MODULE} || git checkout -B autogenerated-${MODULE})
  # - cp -R ~/autorest.cli.debug/generated/magic-modules-input/${MODULE} ~/magic-module-specs/specs
  # - cd ~/magic-module-specs ; git add -A ; git commit -m "autogenerated-${MODULE}" ; git push --set-upstream origin autogenerated-${MODULE}

  # - export MODULE=frontdoor
  # - cd ~/magic-module-specs; git checkout master; (git checkout autogenerated-${MODULE} || git checkout -B autogenerated-${MODULE})
  # - cp -R ~/autorest.cli.debug/generated/magic-modules-input/${MODULE} ~/magic-module-specs/specs
  # - cd ~/magic-module-specs ; git add -A ; git commit -m "autogenerated-${MODULE}" ; git push --set-upstream origin autogenerated-${MODULE}

  # - export MODULE=frontdoorroutingrule
  # - cd ~/magic-module-specs; git checkout master; (git checkout autogenerated-${MODULE} || git checkout -B autogenerated-${MODULE})
  # - cp -R ~/autorest.cli.debug/generated/magic-modules-input/${MODULE} ~/magic-module-specs/specs
  # - cd ~/magic-module-specs ; git add -A ; git commit -m "autogenerated-${MODULE}" ; git push --set-upstream origin autogenerated-${MODULE}

  # - export MODULE=softwareupdateconfiguration
  # - cd ~/magic-module-specs; git checkout master; (git checkout autogenerated-${MODULE} || git checkout -B autogenerated-${MODULE})
  # - cp -R ~/autorest.cli.debug/generated/magic-modules-input/${MODULE} ~/magic-module-specs/specs
  # - cd ~/magic-module-specs ; git add -A ; git commit -m "autogenerated-${MODULE}" ; git push --set-upstream origin autogenerated-${MODULE}

  # - export MODULE=batchapplication
  # - cd ~/magic-module-specs; git checkout master; (git checkout autogenerated-${MODULE} || git checkout -B autogenerated-${MODULE})
  # - cp -R ~/autorest.cli.debug/generated/magic-modules-input/${MODULE} ~/magic-module-specs/specs
  # - cd ~/magic-module-specs ; git add -A ; git commit -m "autogenerated-${MODULE}" ; git push --set-upstream origin autogenerated-${MODULE}

  # - export MODULE=batchapplicationpackage
  # - cd ~/magic-module-specs; git checkout master; (git checkout autogenerated-${MODULE} || git checkout -B autogenerated-${MODULE})
  # - cp -R ~/autorest.cli.debug/generated/magic-modules-input/${MODULE} ~/magic-module-specs/specs
  # - cd ~/magic-module-specs ; git add -A ; git commit -m "autogenerated-${MODULE}" ; git push --set-upstream origin autogenerated-${MODULE}



#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementapi ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementapiissue ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementapiissueattachment ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementapiissuecomment ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementapioperation ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementapioperationpolicy ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementapipolicy ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementapischema ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementapitagdescription ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementapiversionset ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementauthorizationserver ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementbackend ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementcache ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementcertificate ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementdiagnostic ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementgroup ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementidentityprovider ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementlogger ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementopenidconnectprovider ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementpolicy ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementproduct ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementproductpolicy ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementproperty ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/a#pimanagementsignupsetting ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementtag ~/magic-module-specs
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/apimanagementuser ~/magic-module-specs


#
#  - cp -R ~/autorest.cli.debug/generated/magic-modules-input/batchapplication ~/magic-module-specs
#  #- shopt -s globstar; cd ~/autorest.cli.debug/generated/magic-modules-input; cp --parents --no-clobber ./**/ansible.yaml ~/magic-module-specs; cp --parents --no-clobber ./**/terraform.yaml ~/magic-module-specs; cp --parents ./**/api.yaml ~/magic-module-specs
#  #- shopt -s globstar; cd ~/autorest.cli.debug/generated/magic-modules-input/; cp --parents ./**/ansible.yaml ~/magic-module-specs; cp --parents ./**/terraform.yaml ~/magic-module-specs; cp --parents ./**/api.yaml ~/magic-module-specs

# uncomment this to generate magic modules
#  - cd ~/magic-module-specs ; git add -A ; git commit -m "autogenerated-${TRAVIS_BUILD_NUMBER}" ; git push --set-upstream origin autogenerated-${TRAVIS_BUILD_NUMBER}
